sources:
  - ./SwiftyMocky-Example/Shared
  - ./SwiftyMocky-Example/tvOS
  - ./SwiftyMocky-Tests/tvOS
templates:
  - ./Sources/Templates
output:
  ./SwiftyMocky-Tests/tvOS/Mocks
args:
  testable:
    - Mocky_Example_tvOS
  excludedSwiftLintRules:
    - force_cast
    - function_body_length
    - line_length
    - vertical_whitespace
